### ISSUE TITLE
tocMaxDepthToPrint parameter does not work

### ISSUE THREAD

**Issue by tomkuba** [spyhunter99/maven-pdf-plugin#16]
tocMaxDepthToPrint parameter seems to be ignored. Any number I choose is ignored and TOC has always same number of levels. I am working with version 1.5.0.7.
I am not developer, but is it possible that this line resets the value to null? https://github.com/spyhunter99/maven-pdf-plugin/blob/dfb6837a5c6ced3d9d32c7a8871d98d0f5a89b61/src/main/java/com/github/spyhunter99/pdf/plugin/PdfMojo.java#L388

**Comment by spyhunter99** [comment]
I'll look into it

**Comment by spyhunter99** [comment]
cant reproduce it. can you post the relevant section of your pom?

**Comment by tomkuba** [comment]
I found the problem. I was running `mvn site pdf:pdf` and got two different pdf files. One in target/pdf/ folder and one in target/site/ folder. I was looking into wrong one (target/pdf/) all the time and did not notice they are different. The one in target/site works as expected. I' am closing this ticket.
