### ISSUE TITLE
please upgrade Doxia to a current release

### ISSUE THREAD

**Issue by mprins** [spyhunter99/maven-pdf-plugin#17]
current release of doxia is 1.10, which has many improvements especially wrt. markdown processing

**Comment by spyhunter99** [comment]
i've updated it, would you mind testing? I'm not sure what's different between 1.8 and 1.9.2 or what it buys us. hopefully markdown macros

**Comment by mprins** [comment]
I was already using 1.9.1 with an override in my pom file; however current release is 1.10 and has introduced API compatibility problems.

see: https://github.com/mprins/stunning-computing-machine/pull/5/checks?check_run_id=2951238551

perhaps we need to wait for a release of the "doxia-sitetools" as well to restore API compat

**Comment by spyhunter99** [comment]
i was able to get it work, just a pom change.

**Comment by spyhunter99** [comment]
release is cut, should be on central shortly
